apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: project-trigger-template
spec:
  params:
  - name: git-repo-url
    description: URL to the git repo to be cloned
  - name: apikey
    description: Service Account API KEY for interacting with IBM Cloud note the specific syntax of apikey has special relevance to many IBM Cloud resources, so should not be changed.
  - name: path-to-context
    description: The path to the build context, used by Kaniko
    default: .
  - name: path-to-manifest-file
    description: The path to the yaml file describe how to deploy the application. 
    default: manifest.yaml
  - name: api-url
    description: The api url for interacting with ibm cloud
    default: cloud.ibm.com
  - name: ibm-cloud-region
    description: The region where the cluster resides
    default: us-south
  - name: mvn-goals
    description: The Maven goals to be executed
    type: array
    default: ["package"]
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: hello-tekton-build-
    spec:
      serviceAccountName: service-account
      pipelineRef:
        name: project-pipeline
      params:
      - name: path-to-context
        value: $(params.path-to-context)
      - name: path-to-manifest-file
        value: $(params.path-to-manifest-file)
      - name: api-url
        value: $(params.api-url)
      - name: ibm-cloud-region
        value: $(params.ibm-cloud-region)
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: mvn-goals
        type: array
        value: $(params.mvn-goals)
      workspaces:
        - name: git-repo
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: project-pipeline
spec:
  params:
    - name: api-url
    - name: git-repo-url
    - name: path-to-context
    - name: path-to-manifest-file
    - name: ibm-cloud-region
    - name: mvn-goals
      type: array
  workspaces:
    - name: git-repo 
      description: Workspace for holding the cloned source code from the git-repo
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone-repo
    params:
      - name: repository
        value: $(params.git-repo-url)
    workspaces:
      - name: output
        workspace: git-repo
  - name: build-artifact-from-source
    taskRef:
      name: maven-build-java-artifact-from-source
    runAfter:
      - git-clone
    params:
      - name: mvn-goals
        type: array
        value: $(params.mvn-goals)
      - name: path-to-context
        value: $(params.path-to-context)
    workspaces:
      - name: source
        workspace: git-repo
  - name: deploy-image-to-ibm-cloud-functions
    taskRef:
      name: deploy-image-to-ibm-cloud-functions
    runAfter:
      - build-artifact-from-source
    params:
    - name: path-to-manifest-file
      value: $(params.path-to-manifest-file)
    - name: ibm-cloud-region
      value: $(params.ibm-cloud-region)
    - name: api-url
      value: $(params.api-url)
    workspaces:
      - name: source
        workspace: git-repo